Preload script wrappers at import time
pypa/distlib pull request #215
Opened 2024-05-02 20:10 UTC by pfmoore

Pip encountered an issue (https://github.com/pypa/pip/issues/12666) where we can't find the script wrappers because we've uninstalled the running version of pip. Pre-loading the wrapper code into memory when importing `distlib.scripts` avoids this problem.

We can patch this locally, but would it be acceptable as a change here instead?

2024-05-02 20:20 UTC, notatallshaw commented
macos-latest 3.7 is failing because macos-latest has moved from macos-12 to macos-14, and macos-14 does not have Python 3.7 on it.

Given macos-12 is x86 and macos-14 is ARM and distlib tests run so quickly, I would reccomend running against both and excluding Python 3.7 for macos-14/latest, a little like in https://github.com/pypa/pip/pull/12593/files

2024-05-02 20:31 UTC, vsajip requested changes
`WRAPPERS` is only used when `os.name == 'nt' or (os.name == 'java' and os._name == 'nt')`, so this computation suite could also be done only when the above condition is true, right?

2024-05-02 20:36 UTC, pfmoore commented
Good catch - fixed.

2024-05-03 06:49 UTC, merged

2024-05-03 06:54 UTC, vsajip commented
@pfmoore do you need an imminent release with this change? Otherwise I would normally do a release mid-year-ish (unless an urgent issue needs fixing).

2024-05-03 08:46 UTC, pfmoore commented
I don't think it's needed. The pip issue isn't urgent, and we can patch locally in the interim. It's not worth making you do the extra work IMO.

2024-10-17 21:32 UTC, gaborbernat commented
This broke virtualenv Windows zipapps https://github.com/pypa/distlib/issues/235

2024-10-18 10:49 UTC, pfmoore commented
Hmm, sorry about that. I thought that registered finders needed to be compatible with the `ResourceFinder` class. The docs should probably be clearer on what's required - PEP 302 is *extremely* out of date these days, but unfortunately the `importlib.resources` API, which is the stdlib analogue of the distlib resources API, is still pretty unstable and not something I think we should reference 🙁

Maybe we should say that all registered finders must implement the `ResourceFinder` interface? @vsajip what do you think? I can update the docs if that seems reasonable to you.

2024-10-19 10:21 UTC, vsajip commented
>  what do you think

That seems reasonable to me, but what fix do you propose to the changes in this PR? I mean, it looks like Gabor's worked around it, but isn't it better to sort it at source?

2024-10-19 11:00 UTC, pfmoore commented
TBH, I'd assumed it wasn't (easily) fixable at source. Isn't the problem here that virtualenv loads distlib from a location that's registered with a finder that doesn't support iterating over resources?

In [this code](https://github.com/pypa/virtualenv/pull/2783/files#diff-2610f9e5b2d369eec67f7e692282abd30043e8eeafc6adc39fa7ccba3baf4e0aL87), virtualenv registers a custom finder, but it's not clear that the registration satisfies the necessary contract, which says that the finder maker "must return a finder for that package". What constitutes a "finder" isn't clear (and the reference to PEP 302 in that section of the docs further muddies the water) but I'd assume it means a `ResourceFinder` (or at least something that provides the interface that `ResourceFinder` does).

My proposal was simply to make that clearer. In theory, virtualenv is still incorrect, as it doesn't implement methods like `is_container`, or `get_stream`, but I would consider that a practical decision on virtualenv's part, to only implement as much of the interface as it needs to. We could go further and make `ResourceFinder` subclassable, and make `register_finder` *require* that the `finder_maker` returns a `ResourceFinder` subclass, but that's a bigger change than I feel comfortable proposing (or making!)

If, on the other hand, you have a suggestion of how we can find the wrappers using a finder that only implements `find`, I'm happy to have a go at implementing that. But I can't think of a way myself that doesn't require hard coding the names of the wrapper executables.

2024-10-19 15:35 UTC, gaborbernat commented
Yes, my primary complaint I made here is about the documentation not being clear what it actually required And I had to reverse engineer the interface I needed to implement.

2024-10-19 16:01 UTC, pfmoore commented
@gaborbernat @vsajip is #236 sufficient?

2024-10-19 16:44 UTC, vsajip commented
Thank you, Paul, I've merged it. @gaborbernat let us know if you think more is needed.

2024-10-19 17:17 UTC, gaborbernat commented
yeah, that sounds better